#!/usr/bin/env python

import sys, time

lines = map(lambda x: x[:-3].split(), sys.stdin.readlines())

def genTime(dur):
    sec = dur / 1000
    millis = dur - (sec * 1000)
    t = time.gmtime(sec)

    return "%s.%03d" % (time.strftime("%H:%M:%S", t), millis)

def getStart(lines):
    for ts, event, dummy, data in lines:
        if event == "RECORDING_COUNTDOWN":
            recording_id, countdown = data.split(",")
            if int(countdown) == 0:
                return int(ts)
            pass
        pass
    raise "failed to find RECORDING_COUNTDOWN 0"

start = getStart(lines)
    
print "kate {\n"

for ts, event, dummy, data in lines:

    timestamp = int(ts)

    if timestamp < start:
        if event in ['LOGFILE_VERSION', 'SESSION_PARAMETER']: 
            timestamp = start
        else:
            continue
        pass
    
    start_time = genTime(timestamp - start)
    
    print """\tevent {\n\t\t%s --> %s\n\t\t"%s %s %s"\n\t}\n\n""" % (start_time, start_time, event, dummy, data)

    pass

print "}\n"

