name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: gradle build -x test
    - name: Test common (3 tries)
      run: |
        max_tries=3
        try_id=0
        while test $try_id -lt $max_tries; do
          try_id=$[$try_id + 1]
          gradle :common:test && exit 0 || continue
        done
        exit 1
